# Fichier /home/raphael/sms_project/config/config.ini

[MODEM]
port = /dev/ttyUSB0
pin = 1234

[DATABASE]
host = 127.0.0.1
# Assurez-vous que cet utilisateur a les droits sur votre BDD 'sms_db'
user = sms_user
password = password123
database = sms_db

[OPENAI]
api_key = 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


[SATISFACTION]
# Nom de la table pour stocker l'historique des conversations
table = satisfaction_conversations

[FALLBACK]
numero_admin = +33647554678
mots_declencheurs = code, champagne, champ, shamp, bouteille, bulles, taxi, tacsi, transport, navette, chauffeur, uber, départ tardif, late checkout, partir plus tard, check out tard, quitter après, massage, relax, spa, détente, massaj, soin, urgence, urgent, vite, problème grave, souci, bug, panne, cassé, dysfonctionnement, arrivée tardive, j'arrive tard, entrer tard, entrée tardive, je serai en retard, arriver avant, accéder avant, je suis en avance, entrée anticipée, je peux venir avant, rejoindre
